version: 0.2
phase:
  commands:
    - npm install
    - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Alejandro Gavilanes CV.pdf
    - styles/*
    - images/*
    - dist/bundle.js
